#!/bin/bash
if [ "$#" -ne 3 ]; then
  echo "사용법: run [입력폴더] [작업폴더] [출력폴더]"
  exit 1 
fi

input=`realpath $1`
workdir=`realpath $2`
output=`realpath $3`

if [ ! -e ${input} ]; then
  echo "${input} 폴더가 존재하지 않습니다."
  exit 2
fi

if [ ! -e ${workdir} ]; then
  mkdir ${workdir}
fi

if [ ! -e ${output} ]; then
  mkdir ${output}
fi

docker run --rm -v ${input}:/app/input -v ${output}:/app/output -v ${workdir}:/app/workdir jereiard/mutagenesis /app/prep
